language: python

python:
    - "2.7"

env:
  global:
    - PORT=5000
    - HOST=0.0.0.0
    - DEBUG=TRUE

install:
    - pip install -r requirements.txt
    - pip install flake8

services:


before_script:


script:
    - flake8 app.py
    - nosetests -sv tests/
